import { Box, Center, Container } from '@mantine/core';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>GSO System</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container className="box">
        <Center h={724} mx="auto">
          <Box>
            <p className="text-red-400">All elements inside Center are centered in Container.</p>
          </Box>
        </Center>
      </Container>
    </>
  );
}
